### ISSUE TITLE
OPA Chess logos

### ISSUE THREAD

**Issue by ChessGUI** [alyanwarr/OPA-Chess-Engine#2]
![opa chess 1](https://user-images.githubusercontent.com/2707025/28237724-9d701a80-6946-11e7-808b-fea852d4babc.jpg)
![opa chess 2](https://user-images.githubusercontent.com/2707025/28237727-ab385bd2-6946-11e7-9b13-f1ae7c8631b1.jpg)
![opa chess 3](https://user-images.githubusercontent.com/2707025/28237733-b9ccb102-6946-11e7-927a-045675cd60a3.jpg)
![opa chess 4](https://user-images.githubusercontent.com/2707025/28237739-c6284696-6946-11e7-97d6-741c658a26d3.jpg)
![opa chess 5](https://user-images.githubusercontent.com/2707025/28237743-d381de60-6946-11e7-8d97-0c438c86e37d.jpg)
![opa chess 6](https://user-images.githubusercontent.com/2707025/28237749-da3feff8-6946-11e7-95b1-cb21d8567135.jpg)

cf. uploaded chess logos for OPA Chess; **Opa is in Germany a slang for grandpa , granddad or gramp(s)**

I suggest to download the freeware **Photofiltre** http://photofiltre.free.fr/ -and you can easily convert the format into Bitmap and a maximum size of 100x50 that can be used with **Arena/ChessGUI/WinBoard or ChessBase (Fritz-Interface)**

**Comment by alyanwarr** [comment]
Cool, thanks for the suggestion!
